spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:2705/user-details
    username: postgres
    password: majkaskepek
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect